apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtn-k8s-deployment
  labels:
    app: rtn-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtn-k8s
  template:
    metadata:
      labels:
        app: rtn-k8s
    spec:
      imagePullSecrets:
      - name: brightbox-cr
      containers:
      - name: rtn-k8s
        image: cr.brightbox.com/acc-tqs4c/docker/rtn-k8s:latest
        imagePullPolicy: Always
        ports:
        - name: rtn-k8s
          containerPort: 3000
