apiVersion: v1
kind: Service
metadata:
  name: rtn-k8s-service
  labels:
    app: rtn-k8s
  annotations:
    service.beta.kubernetes.io/brightbox-load-balancer-listener-protocol: "http+ws"
    service.beta.kubernetes.io/brightbox-load-balancer-listener-idle-timeout: "6000"
    service.beta.kubernetes.io/brightbox-load-balancer-healthcheck-request: "/"
spec:
  selector:
    app: rtn-k8s
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: rtn-k8s
    protocol: TCP
